### ISSUE TITLE
JPParseAndExitOnError will not exit on every error

### ISSUE THREAD

**Issue by pLeminoq** [openbase/jps#4]
This happens when just the command identifier is given as an argument but the value for it is missing. E.g. if a string property command identifier is **-s** and the program is just run like:

`program -s`

Then an error message get printed but System.exit(255) does not get called.

**Comment by DivineThreepwood** [comment]
Issue has been resolved within 7679f71 where the exception handing has been reimplemented.
JPService does not print any errors at all anymore. Errors are now throws when calling the "parseAndExitOnError" and "getProperty" messages and failing properties are addressed.
